project_django/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.Surveys, name='index'),
    path('<int:pk>/', mainapp.Surveys, name='survey'),

]

project_django/project_survey/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf.urls import include

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('survey/', include("mainapp.urls", namespace='survey')),
    path('admin/', admin.site.urls),
]

project_django/mainapp/models.py
from django.db import models


    
class Surveys(models.Model):
    title = models.TextField(verbose_name='Заголовок опроса')
    description = models.TextField(verbose_name='Описание опроса', blank=True)
    quantity_question = models.IntegerField(verbose_name='Количество вопросов', default=0)
    date_start = models.DateField(auto_now_add=True)
    date_finish = models.DateField()

    def __str__(self):
        return self.title
    


class Questions(models.Model):
    survey_id = models.ForeignKey(Surveys, verbose_name="Номер опроса", on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Текст вопроса')
    type_answer = models.IntegerField(verbose_name='Какой тип вопроса (1 - строка, 2 - один ответ, 3 - несколько ответов)', default=1)
    # Далее один обязательный ответ, и остальные при необходимости будут заполняться
    var_answer1 = models.TextField(verbose_name='1 вариант')
    var_answer2 = models.TextField(verbose_name='2 вариант', blank=True)
    var_answer3 = models.TextField(verbose_name='3 вариант', blank=True)
    var_answer4 = models.TextField(verbose_name='4 вариант', blank=True)
    
    def __str__(self):
        return self.text
    


class Result(models.Model):
    id_user = models.CharField(verbose_name='ID пользователя', max_length=64, unique=False)
    survey_id = models.ForeignKey(Surveys, verbose_name="Номер опроса", on_delete=models.CASCADE)
    question_id = models.ForeignKey(Questions, verbose_name="Номер вопроса", on_delete=models.CASCADE)
    answer1 = models.TextField(verbose_name='Вернувшийся с формы ответ на вопрос 1')
    answer2 = models.TextField(verbose_name='Вернувшийся с формы ответ на вопрос 1', blank=True)
    answer3 = models.TextField(verbose_name='Вернувшийся с формы ответ на вопрос 1', blank=True)
    answer4 = models.TextField(verbose_name='Вернувшийся с формы ответ на вопрос 1', blank=True)


    def __str__(self):
        return self.id_user

project_django/mainapp/views.py
from django.shortcuts import render

from .models import Surveys, Result, Questions

# Create your views here.
def main(request):
    title = 'Главная'

    text = Surveys.objects.all()
    content = {"title": title, "text": text}

    return render(request, 'mainapp/index.html', content)

def survey(request, pk=None):
    print(type(pk))
    return render(request, "mainapp/survey.html")

project_django/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock css %}
    
</head>

<body>
    {% block menu %}
        <br>
    <div class="row">
    <div class="col-sm-2"></div>
    <nav class="navbar navbar-light bg-light col-sm-7">
        <a class="navbar-brand" href="/">
        <img src="{% static 'icon/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Небольшой опросник
        </a>
    </nav>
    <button type="button" class="btn btn-primary btn-sm col-sm-1">Админка</button>
    <div class="col-sm-2"></div>
    </div>

    <br><br>
    {% endblock menu %}

    {% block content %}

    {% endblock content %}

    {% block bootstrap %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Подключаем Bootstrap JS -->    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% endblock bootstrap %}
</body>
</html>

project_django/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>

{% block content %}
  <div class="row">
  <div class="col-sm-2"></div>     

        {% for i in text %}
          <div class="col-sm-4">
          <div class="card text-white bg-info mb-3">
            <div class="card-body">
                <h4 class="card-title">{{i.title}}</h4>
                <h5 class="card-title">Ответье на 4 вопроса мы сами угадаем кто вы</h5>
                <h6 class="card-text">Дата начала:<p>{{i.date_start|date:"j E Y"}}</p> Дата Окончания:<p>{{i.date_finish|date:"j E Y"}}</p></h6>
              <a href="{% url 'survey:index' %}" class="btn btn-primary">Переход куда-нибудь</a>
            </div>
          </div>
        </div>
          {% if forloop.counter|divisibleby:"2" %}
              <div class="col-sm-2"></div>
              <br>
              <div class="col-sm-2"></div>
          {% endif %}        
        {% endfor %}
  </div>

        
    
{% endblock content %}

project_django/mainapp/templates/mainapp/survey.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <div class="col-sm-2"></div>
    <div class="card text-center col-sm-8">
        <div class="card-header">
          Featured
        </div>
        <div class="card-body">
          <h5 class="card-title">Специальный заголовок</h5>
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">Переход куда-нибудь</a>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
      <div class="col-sm-2"></div>
    </div>
{% endblock content %}